### ISSUE TITLE
User can view details of any player on chess.com

### ISSUE THREAD

**Issue by Jktanisaka** [Jktanisaka/ajax-project#1]
## 💰 Motivation
Chess.com users will want to be able to look at details of any player

## 📐 Plan

Create a search box that can be used to search Chess.com usernames and will display their stats once found.

## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/96153171/163845946-c50ac343-4bff-4d6c-8137-88abaca585de.png)
![image](https://user-images.githubusercontent.com/96153171/163845988-ea870820-f878-49f7-a16a-7460e5d8eeb7.png)

## ✅ Task List

- [x] create HTML skeleton and link all necessary CSS and JS files.
- [x] Create all necessary HTML elements and CSS styling
- [x] Make sure that all styling looks good on both mobile and desktop screens
- [x] use media query to make sure the name shows up in the correct spot for mobile/desktop
- [x] Access Chess.com API for necessary information
- [x] add event listener to listen for a submit event on the form
- [x] take the text content of the input and search chess.com for the username
- [x]  Create data model with an entryID to keep track of objects
- [x] Store Chess.com data into an object
- [x] use DOM to query all text and image fields that need to be updated
- [x] update dom info with data from Chess.com
- [x] apply default image if no image is available
- [x] create view swap function
- [x] make sure clicking on search brings up correct view
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality in a private browsing session.
- [x] Fix all errors.
