### ISSUE TITLE
User can add an entry to a list

### ISSUE THREAD

**Issue by Jktanisaka** [Jktanisaka/ajax-project#2]
## 💰 Motivation
Chess.com users will want to be able to add players to a list

## 📐 Plan

add a player to the list

## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/96153171/163847089-b2095398-bf93-483a-aa31-42b4fde479fb.png)

## ✅ Task List
- [x] Create new button and style appropriately
- [x] make sure newEntry Object has a unique ID 
- [x] if button is pushed, add the newEntry object to the data model (data.entries) and increment the nextID by 1
- [x] make sure the list includes the expected object
- [x] store data in localstorage
- [x] remove any unnecessary css
- [x] make sure everything functions in a private browser
- [x] fix any bugs
