### ISSUE TITLE
User can view the list

### ISSUE THREAD

**Issue by Jktanisaka** [Jktanisaka/ajax-project#3]
## 💰 Motivation
User will want to view the list they created

## 📐 Plan

Display the created list in reverse-chronological order

## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/96153171/163847341-049fea11-2e93-4025-a0e5-a515771ed4df.png)

## Task List
- [x] create new data-view for list
- [x] create button for view list in the header
- [x] use DOM to create player profile for a player object 
- [x] loop through all entries in data.entries and use DOM to append each entry to the list
- [x] create property on data model to store the most recently searched player
- [x] after player is added, use recently searched property to make dom tree for that player and prepend to the list
- [x] create button to take user back to search view when clicked
- [x] create button to take user to view the list when clicked
- [x] make view switch to list after entry has been added
- [x] remove any unnecessary css styling
- [x] make sure everything stilll works in a private browser
