### ISSUE TITLE
User can sort the list

### ISSUE THREAD

**Issue by Jktanisaka** [Jktanisaka/ajax-project#4]
## 💰 Motivation
Users will want to be able to sort the list by rank

## 📐 Plan
create a dropdown that will allow users to sort the list by their preferred rating

## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/96153171/163847631-8ee0bf48-30bc-4e5e-8d0e-ae08f583b00d.png)

## ✅ Task List
- [x] create dropdown to allow user to select between Rapid and Blitz with "sort" as the placeholder
- [x] use lodash to sort the entries accordingly
- [x] create new entry on data model for Blitz and Rapid and use it to store the sorted entries accordingly
- [x] if list is sorted, remove the current list and replace it with a list created from data.Blitz/data.Rapid
- [x] clean up any unnecessary code/CSS
- [x] check functionality in a private browser
