### ISSUE TITLE
User can delete an entry

### ISSUE THREAD

**Issue by Jktanisaka** [Jktanisaka/ajax-project#5]
## 💰 Motivation
Users will want to be able to delete an entry from the list

## 📐 Plan
add a button to allow users to delete an entry and return the updated list

## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/96153171/163847812-f4c98668-29be-4b71-8c41-030fb1e980a6.png)

## ✅ Task List
- [x] create delete icon on each profile card
- [x] listen for delete icon click
- [x] create modal with options to delete or cancel
- [x] if canceled, remove modal
- [x] if deleted, remove entry from data model and from the page
- [x] use entryID's to determine which entry to delete
- [x] after entry is deleted, make sure list is updated
- [x] remove any unnecessary code/CSS
- [x] verify functionality in a private browser
